### ISSUE TITLE
Can't install BIMP plugin to flatpak Gimp on my linux mint

### ISSUE THREAD

**Issue by street-spirit** [flathub/org.gimp.GIMP.Plugin.BIMP#4]
Could someone please help me and explain to me what should i do to install that BIMP plugin to my GIMP (Fltapak) ? I'm using linux mint. I've done this: sudo apt-get install libgimp2.0-dev libgegl-dev. But when i try to "make && make install" it gives me errors. i reckon it's because my gimp is fltapack and plugins are not supposed to be installed like regular plugins to regular linux apps if you have flatpak app. Could someone help me with that?

**Comment by hfiguiere** [comment]
`flatpak install org.gimp.GIMP.Plugin.BIMP//2-40`


That's all you need to do.

**Comment by street-spirit** [comment]
i'm getting this error:

error: REMOTE and REF must be specified

-- 


Nov 3, 2021, 14:50 by ***@***.***:

**Comment by hfiguiere** [comment]
You must have a antique version of flatpak....

Try `flatpak install flathub org.gimp.GIMP.Plugin.BIMP//2-40`, but this assume that `flathub` is the name of the remote you installed GIMP flatpak from.

**Comment by street-spirit** [comment]
It worked!!!! I appreciate your help so much! I know that it's actually possible for me to switch to windows or macos and have all the apps needed easily available there! But since 3 years ago i had Linux installed on my only laptop without any alternatives, like the second OS or another computer (my friend who also likes Linux done it to me) i never thought about going back to Windows cause i realized pretty quick that Linux Mint is the best OS for me! Usually I manage to get everything i need from Linux myself but sometimes it gets too hard for me to handle Linux and outside help is needed... It's nice that there're people here who are always ready to help one another! THANKS A LOT!!!
